name: run-tri-contributeurs
on: pull_request
jobs:
  build:
    name: Run tri-contributeurs.py
    runs-on: ubuntu-latest
    steps:
    - name: Pull Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Run script
      run: python tri-contributeurs.py
    - name: Push Back Formatted Code
      run: |
        # configure git
        git config --global user.name "Digifab"
        git config --global user.email "digifab-dev@users.noreply.github.com"
        git commit -a -m "Tri des contributeurs"
        git push
